const categoryActionTypes = {
  ADD_CATEGORY: "ADD_CATEGORY",
  REMOVE_CATEGORY: "REMOVE_CATEGORY",
  DISPLAY_CATEGORY: "DISPLAY_CATEGORY",
  DISPLAY_CATEGORIES: "DISPLAY_CATEGORIES",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
};

export default categoryActionTypes;
