const paymentActionTypes = {
  ADD_PAYMENT: "ADD_PAYMENT",
  REMOVE_PAYMENT: "REMOVE_PAYMENT",
  DISPLAY_PAYMENT: "DISPLAY_PAYMENT",
  DISPLAY_PAYMENTS: "DISPLAY_PAYMENTS",
  UPDATE_PAYMENT: "UPDATE_PAYMENT",
};

export default paymentActionTypes;
