const productActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  DISPLAY_PRODUCT: "DISPLAY_PRODUCT",
  DISPLAY_PRODUCTS: "DISPLAY_PRODUCTS",
};

export default productActionTypes;
