const storeActionTypes = {
  ADD_STORE: "ADD_STORE",
  REMOVE_STORE: "REMOVE_STORE",
  DISPLAY_STORE: "DISPLAY_STORE",
  DISPLAY_STORES: "DISPLAY_STORES",
  UPDATE_STORE: "UPDATE_STORE",
};

export default storeActionTypes;
