const userActionTypes = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  RESET_PASSWORD: "RESET_PASSWORD",
  PERSIST_MYSELF: "PERSIST_MYSELF",
  DISPLAY_ALL_USERS: "DISPLAY_ALL_USERS",
  DISPLAY_USER: "DISPLAY_USER",
  QUERY_USERS: "QUERY_USERS",
  UPDATE_USER: "UPDATE_USER",
  REMOVE_USER: "REMOVE_USER",
};

export default userActionTypes;
